config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/chat_with_image', to: 'home#chat_with_image', as: 'chat_with_image_home'

  resources :types
  resources :familles
  resources :plantes

  get '/chat/ask', to: 'chat#ask', as: 'chat_ask'
  post 'chat/submit', to: 'chat#submit', as: 'chat_submit'

  
  get 'rechercher', to: 'plantes#rechercher', as: 'rechercher'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/plante.rb
class Plante < ApplicationRecord
  belongs_to :famille

  validates :nom, presence: { message: "Le nom de la plante est obligatoire pour faciliter son identification." }, uniqueness: { case_sensitive: false, message: " doit être unique." } 

  def self.condition_ete 
    {
    'ete_royan_veranda' => 'En été à Royan dans une véranda',
    'ete_royan_interieur' => 'En été à Royan en intérieur',
    'ete_royan_exterieur'=> 'En été à Royan dans le jardin',
    'ete_paris_interieur'=> 'En été à Paris en interieur',
    'ete_paris_exterieur' => 'En été à Paris en exterieur'
  }
  end

  def self.condition_hiver
    {
    'hiver_royan_veranda' => 'En hiver à Royan dans une véranda',
    'hiver_royan_interieur' => 'En hiver à Royan en intérieur',
    'hiver_royan_exterieur' => 'En hiver à Royan dans le jardin',
    'hiver_paris_interieur' => 'En hiver à Paris en interieur',
    'hiver_paris_exterieur' => 'En hiver à Paris en exterieur'
  }
  end

  def condition_ete_human_readable
    self.class.condition_ete[self.condition_ete]
  end

  def condition_hiver_human_readable
    self.class.condition_hiver[self.condition_hiver]
  end

end

app/controllers/plantes_controller.rb
class PlantesController < ApplicationController
  before_action :set_plante, only: %i[ show edit update destroy ]

  # GET /plantes or /plantes.json
  def index
    @plantes = Plante.all
  end

  # GET /plantes/1 or /plantes/1.json
  def show
    
  end


  # GET /plantes/new
  # app/controllers/plantes_controller.rb
  def new
    @plante = Plante.new
    @familles = Famille.all # Récupère toutes les familles pour les afficher dans le formulaire
    #@plante.famille_id = params[:famille_id] if params[:famille_id]
    # Assurez-vous d'ajouter une logique pour gérer le cas où `famille_id` n'est pas fourni

  end

  # GET /plantes/1/edit
  def edit
    @plante = Plante.find(params[:id])
    @familles = Famille.all
  end

  # POST /plantes or /plantes.json
  def create
    @plante = Plante.new(plante_params)

    respond_to do |format|
      if @plante.save
        format.html { redirect_to plante_url(@plante), notice: "Plante was successfully created." }
        format.json { render :show, status: :created, location: @plante }
      else
        @familles = Famille.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plantes/1 or /plantes/1.json
  def update
    respond_to do |format|
      if @plante.update(plante_params)
        format.html { redirect_to plante_url(@plante), notice: "Plante was successfully updated." }
        format.json { render :show, status: :ok, location: @plante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plantes/1 or /plantes/1.json
  def destroy
    @plante.destroy!

    respond_to do |format|
      format.html { redirect_to plantes_url, notice: "Plante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def rechercher
    @query = params[:query]
    @resultats = Plante.where("nom LIKE ?", "%#{@query}%") if @query.present?
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plante
      @plante = Plante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plante_params
      params.require(:plante).permit(:latitude, :longitude, :nom, :image_url, :famille_id, :observation, :conseil_expert, :nom_scientifique, :arrosage_ete, :arrosage_hiver, :condition_ete, :condition_hiver, :sante, :probleme, :conseil, :besoin)
    end
end

app/helpers/plantes_helper.rb
module PlantesHelper
end

app/views/plantes/_form.html.erb
<%= form_with(model: plante, class: "contents") do |form| %>
  <% if plante.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(plante.errors.count, "error") %> prohibited this plante from being saved:</h2>

      <ul>
        <% plante.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @plante.famille_id %>
    <%= form.hidden_field :famille_id, value: @plante.famille_id %>
  <% end %>

  <div class="field">
    <%= form.label :famille_id, "Famille" %>
    <%= form.collection_select :famille_id, @familles, :id, :nom, prompt: "Sélectionnez une famille" %>
  </div>

  <div class="my-5">
    <%= form.label :nom, "Nom commun" %>
    <%= form.text_field :nom, placeholder: "Ex: Pied d'éléphant.", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :nom_scientifique, "Nom scientifique" %>
    <%= form.text_field :nom_scientifique, placeholder: "Ex: Beaucarnea recurvata.", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :condition_ete , "Condition de vie en été" %>
    <%= form.select :condition_ete, Plante.condition_ete.map {|key, value| [value, key]} , { include_blank: true } %>
  </div>

  <div class="my-5">
    <%= form.label :arrosage_ete %>
    <%= form.text_area :arrosage_ete, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :condition_hiver, "Condition de vie en hiver" %>
    <%= form.select :condition_hiver, Plante.condition_hiver.map { |key, value| [value, key] }, { include_blank: true } %>
  </div>

  <div class="my-5">
    <%= form.label :arrosage_hiver %>
    <%= form.text_area :arrosage_hiver, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image_url, "URL de l'image" %>
    <%= form.text_field :image_url, placeholder: "URL de l'image", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sante, "Comment savoir si elle va bien ?" %>
    <%= form.text_area :sante, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :probleme, "Quels sont les signes de problème ?" %>
    <%= form.text_area :probleme, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :conseil, "Quels conseils pouvez-vous me donnés ?" %>
    <%= form.text_area :conseil, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :besoin, "Quelles sont ces besoins nutritionnels ?" %>
    <%= form.text_area :besoin, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :conseil_expert, "Les conseils de papi" %>
    <%= form.text_area :conseil_expert, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/plantes/_plante.html.erb
<div id="<%= dom_id plante %>">
  <p class="h1-like">
    <div class="markdown-content mb-4">
      <h1><%= plante.nom.capitalize %></h1>
      <h1><%= plante.nom_scientifique %></h1>
    </div>
  </p>

  <% if @plante.image_url.present? %>
  <p class="my-5">
    <div class="markdown-content mb-4">
      <%= image_tag(plante.image_url, width: "500", alt: "Image de la plante") %>
    </div>
  </p>
  <% end %>

  <div class="h2-like">Origine:</div>
  <div id="map" style="height: 400px;"></div>

  <script>
      var map = L.map('map').setView([<%= @plante.latitude %>, <%= @plante.longitude %>], 3); // Zoom et position
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
      }).addTo(map);

      var marker = L.marker([<%= @plante.latitude %>, <%= @plante.longitude %>]).addTo(map)
      .bindPopup('<%= @plante.nom_scientifique %>')
      .openPopup();
  </script>

  <div class="h2-like">Condition de vie en été:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.condition_ete_human_readable)) %>
    </div>

  <div class="h2-like">Arrosage en été</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.arrosage_ete)) %>
    </div>
  

  <div class="h2-like">Condition de vie en hiver:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.condition_hiver_human_readable)) %>
    </div>
  

  <div class="h2-like">Arrosage en hiver:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.arrosage_hiver)) %>
    </div>
  

  <div class="h2-like">Etat de santé:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.sante)) %>
    </div>
  

  <div class="h2-like">Signes de problèmes:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.probleme)) %>
    </div>
  

  <div class="h2-like">Conseils:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.conseil)) %>
    </div>
  

  <div class="h2-like">Besoins nutritionnels:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.besoin)) %>
    </div>
  
  <div class="h2-like">Conseils de papi:</div>
    <div class="markdown-content mb-4">
      <%= sanitize(markdown_to_html(@plante.conseil_expert)) %>
    </div>

  <% if action_name != "show" %>
    <%= link_to "Show this plante", plante, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this plante", edit_plante_path(plante), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/plantes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing plante</h1>
  <br>
  <%= render "form", plante: @plante %>

  <%= link_to "Voir cette plante", @plante, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600-100 inline-block font-medium" %>
  <%= link_to "Retour aux plantes", plantes_path, class: "ml-2 rounded-lg py-3 px-5 bg-orange-600-100 inline-block font-medium" %>
</div>

app/views/plantes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

    <div class="h1-like">Liste des plantes</div>

  <table id="plantes" class="mx-auto">
    <tfoot>
      <tr>
        <td colspan="3">
          <div class="mt-8">
            <%= link_to 'Nouvelle plante', new_plante_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
            <%= link_to "Retour aux types", types_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
            <%= link_to "Retour aux familles", familles_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
          </div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @plantes.each do |plante| %>
        <tr class="<%= cycle('bg-green-50', 'bg-white') %>">

          <td class="px-2 py-3">
            <%= image_tag(plante.image_url, class: 'w-40') %>
          </td>
          <td class="px-2 py-3">
            <%= plante.nom %>
          </td>
          <td class="px-2 py-3">
            <%= plante.nom_scientifique %>
          </td>
          
          <td class="px-3">
            <ul>
              <li>
                <%= link_to 'Show', plante, class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Edit', edit_plante_path(plante), class: 'hover:underline' %>
              </li>
              <li>
                <%= link_to 'Destroy', plante, class: 'hover:underline', data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
 
    

app/views/plantes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nouvelle plante</h1>
  <br>
  
  <%= render "form", plante: @plante %>

  <%= link_to "Back to familles", familles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/plantes/rechercher.html.erb
    <h3 class="font-bold text-2xl mt-4">Résultat de la recherche pour "<%= @query %>":</h3>

      <% if @resultats.present? %>
        <ul class="list-disc pl-8">
          <% @resultats.each do |plante| %>
            <li><%= link_to plante.nom.capitalize, plante_path(plante), class: "link-plante" %></li>
          <% end %>
        </ul>
      <% else %>
        <p>Aucune plante trouvé.</p>
      <% end %>

app/views/plantes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @plante %>

    <%= link_to "Editer cette plante", edit_plante_path(@plante), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Retour aux plantes", plantes_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Detruire cette plante", plante_path(@plante), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-600 inline-block font-medium" %>
    </div>
    <%= link_to "Retour aux familles", familles_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>