config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/chat_with_image', to: 'home#chat_with_image', as: 'chat_with_image_home'

  resources :types
  resources :familles
  resources :plantes

  get '/chat/ask', to: 'chat#ask', as: 'chat_ask'
  post 'chat/submit', to: 'chat#submit', as: 'chat_submit'

  
  get 'rechercher', to: 'plantes#rechercher', as: 'rechercher'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/famille.rb
class Famille < ApplicationRecord
  has_many :plantes, dependent: :destroy
  belongs_to :type

  validates :nom, uniqueness: { case_sensitive: false, message: " doit être unique." }
  
  validates :nom, presence: { message: "Le nom de la famille est obligatoire pour faciliter son identification." }

  enum origine: {
    europe: 'Europe',
    amerique_du_sud: 'Amérique du Sud',
    amerique_centrale: 'Amerique Centrale',
    amerique_du_nord: 'Amérique du Nord',
    asie: 'Asie',
    afrique_du_sud: 'Afrique du Sud',
    afrique_du_nord: 'Afrique du Nord',
    oceanie: 'Océanie'
  }

  def origine_human_readable
    self.class.origines[self.origine]
  end

  
end

app/controllers/familles_controller.rb
class FamillesController < ApplicationController
  before_action :set_famille, only: %i[ show edit update destroy ]

  # GET /familles or /familles.json
  def index
    @familles = Famille.includes(:plantes).all
  end

  # GET /familles/1 or /familles/1.json
  def show
    @famille = Famille.find(params[:id])
  end

  # GET /familles/new
  def new
    @famille = Famille.new
    @famille.type_id = params[:type_id] if params[:type_id]
  end

  # GET /familles/1/edit
  def edit
  end

  # POST /familles or /familles.json
  def create
    @famille = Famille.new(famille_params)
  
    respond_to do |format|
      if @famille.save
        format.html { redirect_to @famille, notice: 'Famille was successfully created.' }
        format.json { render :show, status: :created, location: @famille }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /familles/1 or /familles/1.json
  def update
    respond_to do |format|
      if @famille.update(famille_params)
        format.html { redirect_to famille_url(@famille), notice: "Famille was successfully updated." }
        format.json { render :show, status: :ok, location: @famille }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @famille.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familles/1 or /familles/1.json
  # app/controllers/familles_controller.rb
  def destroy
    @famille = Famille.find(params[:id])
    if @famille.plantes.empty?
      @famille.destroy
      redirect_to familles_path, notice: 'Famille détruite avec succès.'
    else
      redirect_to @famille, alert: 'Cette famille ne peut pas être détruite car elle a des plantes rattachées.'
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_famille
      @famille = Famille.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def famille_params
      params.require(:famille).permit(:nom, :type_id, :origine, :plantation, :temperature, :arrosage, :substrat, :rempotage, :taille, :bouturage, :maladie, :origine_precise, :temperature_precise)
    end
end

app/helpers/familles_helper.rb
module FamillesHelper
end

app/views/familles/_famille.html.erb
<% @familles.each do |famille| %>
  <div id="<%= dom_id(famille) %>">
    <p class="h1-like">
      <%= famille.nom %>
    </p>
    
    
    <%= link_to 'Ajouter une Plante', new_plante_path(famille_id: famille.id), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <!-- Liens pour voir, éditer, etc. -->
  </div>
<% end %>

app/views/familles/_form.html.erb
<%= form_with(model: famille, class: "contents") do |form| %>
  <% if famille.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(famille.errors.count, "error") %> prohibited this famille from being saved:</h2>

      <ul>
        <% famille.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <% if famille.type_id %>
    <div class="h1-like">
      <%= form.hidden_field :type_id %>
      <%= Type.find(@famille.type_id).nom.capitalize %>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nom, class: "h2-like" %>
    <%= form.text_field :nom, placeholder: "Ex. Famille des crassulacées.", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :origine, class: "h2-like" %>
    <%= form.select :origine, Famille.origines.keys.map { |origine| [origine.humanize, origine] }, { include_blank: true } %>
  </div>

  <div class="my-5">
    <%= form.label :origine_precise, class: "h2-like" %>
    <%= form.text_area :origine_precise, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :substrat, class: "h2-like" %>
    <%= form.text_area :substrat, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :temperature, class: "h2-like" %>
    <%= form.text_field :temperature, rows: 4, placeholder: "Ex: Entre 5 et 30°", class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :temperature_precise, class: "h2-like" %>
    <%= form.text_area :temperature_precise, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :arrosage, class: "h2-like" %>
    <%= form.text_area :arrosage, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rempotage, class: "h2-like" %>
    <%= form.text_area :rempotage, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :plantation, class: "h2-like" %>
    <%= form.text_area :plantation, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :taille, class: "h2-like" %>
    <%= form.text_area :taille, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bouturage, class: "h2-like" %>
    <%= form.text_area :bouturage, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :maladie, class: "h2-like" %>
    <%= form.text_area :maladie, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/familles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing famille</h1>

  <%= render "form", famille: @famille %>

  <%= link_to "Show this famille", @famille, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to familles", familles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/familles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-8">
    <div class="h1-like">Familles de plantes</div>
  </div>

  <% @familles.each do |famille| %>
    <div class="famille mb-8">
      <div class="h1-like"><%= famille.nom.upcase %></div>
        <div class="h3-like"><%= famille.type&.nom&.capitalize %></div>

      <h3 class="font-bold text-2xl mt-4">Plantes associées :</h3>
      <% if famille.plantes.exists? %>
        <ul class="list-disc pl-8">
          <% famille.plantes.each do |plante| %>
            <li><%= link_to plante.nom.capitalize, plante_path(plante), class: "link-famille" %></li>
          <% end %>
        </ul>
      <% else %>
        <p>Aucune plante associée. <%= link_to "Ajouter une nouvelle plante", new_plante_path(famille_id: famille.id), class: "text-blue-600 hover:underline" %></p>
      <% end %>
      <br>
      <%= link_to "Voir cette famille", famille_path(famille.id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
      <%= link_to "Modifier cette famille", edit_famille_path(famille), class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
      <%= link_to "Retour aux types", types_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
    </div>
  <% end %>
</div>

app/views/familles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New famille</h1>

  <%= render 'form', famille: @famille %>

  <%= link_to "Back to familles", familles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/familles/show.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  
    <div class="print-header">
      <div class="h2-like"><%= @famille.type.nom.upcase %></div>
    </div>

    <br>
    <div class="print-main">
      <div class="h1-like"><%= @famille.nom.upcase %></div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <div class="print-footer">
      <div class="h2-like">Origine:</div>
        <div class="markdown-content mb-4">
          <%= @famille.origine_human_readable %>
        </div>
    </div>

    <br>

    <div class="page-break"></div>

    <div class="flex justify-between items-center">
      <div class="h2-like">Plantes associées :</div><br>
        <div class="hide-on-print">
          <%= link_to 'Créer une nouvelle plante pour cette famille', new_plante_path(famille_id: @famille.id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
        </div>
    </div>
  <br>
  <% if @famille.plantes.any? %>
    <div class="grid grid-cols-2 gap-4">
      <% @famille.plantes.each do |plante| %>
        <div class="plante mb-6">
          <div class="h2-like"><%= link_to plante.nom.capitalize, plante_path(plante), class: "link-famille" %></div>
          <br>
          <% if plante.image_url.present? %>
            <%= image_tag(plante.image_url, alt: plante.nom, class: "plante-image") %>
          <% end %>
          <br>
          <div class="plante-details">
            <h3><strong>Conseils d'expert:</strong></h3>
            <p><%= sanitize(markdown_to_html(plante.conseil_expert)) %></p>
          </div>

        </div>
      <% end %>
    </div>
  <% else %>
    <p>Aucune plante associée. <%= link_to "Ajouter une nouvelle plante", new_plante_path(famille_id: @famille.id), class: "text-blue-600 hover:underline" %></p>
  <% end %>

<div class="page-break"></div>

<p><div class="h2-like">Origine precise :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.origine_precise)) %>
  </div>
</p>

<p><div class="h2-like">Substrat :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.substrat)) %>
  </div>
</p>

<p><div class="h2-like">Temperature :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.temperature)) %>
  </div>
</p>

<p><div class="h2-like">Temperature precise:</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.temperature_precise)) %>
  </div>
</p>

<p><div class="h2-like">Arrosage :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.arrosage)) %>
  </div>
</p>

<% if @famille.rempotage.present? %>
<p><div class="h2-like">Rempotage :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.rempotage)) %>
  </div>
</p>
<% end %>

<% if @famille.plantation.present? %>
<p><div class="h2-like">Plantation :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.plantation)) %>
  </div>
</p>
<% end %>

<p><div class="h2-like">Taille :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.taille)) %>
  </div>
</p>

<p><div class="h2-like">Bouturage :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.bouturage)) %>
  </div>
</p>

<p><div class="h2-like">Maladie :</div>
  <div class="markdown-content mb-4">
    <%= sanitize(markdown_to_html(@famille.maladie)) %>
  </div>
</p>

  <div class="hide-on-print">
  <div class="mt-8">
    <%= link_to "Modifier cette famille", edit_famille_path(@famille), class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
    <%= link_to "Retour aux familles", familles_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>

    <% if @famille.plantes.empty? %>
      <%= link_to 'Détruire cette famille', @famille, data: {turbo_method: :delete, turbo_confirm: "'Êtes-vous sûr ? Cette action est irréversible.'"}, class: "rounded-lg py-3 px-5 bg-red-600 text-white font-medium" %>
    <% end %>

    <%= link_to "Retour aux types", types_path, class: "rounded-lg py-3 px-5 bg-orange-600 text-white font-medium" %>
  </div>
  </div>
</div>