config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/chat_with_image', to: 'home#chat_with_image', as: 'chat_with_image_home'

  resources :types
  resources :familles
  resources :plantes

  get '/chat/ask', to: 'chat#ask', as: 'chat_ask'
  post 'chat/submit', to: 'chat#submit', as: 'chat_submit'

  
  get 'rechercher', to: 'plantes#rechercher', as: 'rechercher'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
    
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type = Type.find(params[:id])
    if @type.familles.empty?
      @type.destroy
      redirect_to types_path, notice: 'Type détruit avec succès.'
    else
      redirect_to @type, alert: 'Ce type ne peut pas être détruit car il a des familles rattachées.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:nom, :description, :caracteristique)
    end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, class: "contents") do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="my-5">
    <%= form.label :nom, class: "h2-like" %>
    <%= form.text_field :nom, placeholder: "Ex. Plante grasse, Arbres etc...", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description, class: "h2-like" %>
    <%= form.text_area :description, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :caracteristique, class: "h2-like" %>
    <%= form.text_area :caracteristique, rows: 4, placeholder: "Vous pouvez utiliser la syntaxe Markdown ici...",class: "markdown-content block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/types/_type.html.erb
  <div id="<%= dom_id(type) %>">
  
    <p class="h1-like">
      <div class="markdown-content mb-4">
        <h1><%= link_to type.nom.capitalize, type_path(type), class: "h2 class='my-5'" %></h1>
      </div>
    </p>

    <h3 class="font-bold text-2xl mt-4">Familles associées :</h3><br>
      <% if type.familles.any? %>
        <ul class="list-disc pl-8">
          <% type.familles.each do |famille| %>
            <li><%= link_to famille.nom, famille_path(famille), class: "link-famille" %></li>
          <% end %>
        </ul>
      <% else %>
        <p>Aucune famille associée. <%= link_to "Ajouter une nouvelle famille.", new_famille_path(type_id: type.id), class: "text-blue-600 hover:underline" %></p>
      <% end %>
      <br>
      
    <p><div class="h2-like">Description:</div>
      <div class="markdown-content mb-4">
        <%= sanitize(markdown_to_html(@type.description)) %>
      </div>
    </p>

    <p><div class="h2-like">Caracteristique:</div>
      <div class="markdown-content mb-4">
        <%= sanitize(markdown_to_html(@type.caracteristique)) %>
      </div>
    </p>

    
  </div>

app/views/types/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editer le type</h1>

  <%= render "form", type: @type %>

  <%= link_to "Retour aux types", types_path, class: "ml-2 rounded-lg py-3 px-5 bg-orange-600 inline-block font-medium" %>
</div>

app/views/types/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-8">
    <div class="h1-like">Types de plantes</div>
    <%= link_to "Créer un nouveau type", new_type_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>

  <% @types.each do |type| %>
    <div class="flex justify-between items-center mb-4">
      <div class="h1-like"><%= type.nom.capitalize %></div>
      <%= link_to "Voir", type_path(type), class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium" %>
    </div>

    <div class="flex justify-between items-center">
      <div class="h2-like">Familles associées :</div>
      <%= link_to "Créer une nouvelle famille", new_famille_path(type_id: type.id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
    </div>

    <% if type.familles.any? %>
      <ul class="list-disc ml-6">
        <% type.familles.each do |famille| %>
          <li><div class="h3-like" ><%= link_to famille.nom, famille_path(famille), class: "link-famille" %></div></li>
        <% end %>
      </ul>
    <% else %>
      <p>Aucune famille associée.</p>
    <% end %>
    <hr class="mt-4">
  <% end %>
  <br><br>
</div>

app/views/types/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nouveau type de plante</h1>

  <%= render "form", type: @type %>

  <%= link_to "Retour aux types de plantes", types_path, class: "ml-2 rounded-lg py-3 px-5 bg-orange-600 inline-block font-medium" %>
</div>

app/views/types/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @type %>

    <%= link_to "Editer ce type", edit_type_path(@type), class: "ml-2 rounded-lg py-3 px-5 bg-orange-600 inline-block font-medium" %>
    
    <%= link_to "Retour aux types", types_path, class: "ml-2 rounded-lg py-3 px-5 bg-orange-600 inline-block font-medium" %>

    <div class="inline-block ml-2">
      <%= button_to "Detruire ce type", type_path(@type), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-600 inline-block font-medium" %>
    </div>
  </div>
</div>