config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/chat_with_image', to: 'home#chat_with_image', as: 'chat_with_image_home'

  resources :types
  resources :familles
  resources :plantes

  get '/chat/ask', to: 'chat#ask', as: 'chat_ask'
  post 'chat/submit', to: 'chat#submit', as: 'chat_submit'

  
  get 'rechercher', to: 'plantes#rechercher', as: 'rechercher'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat_with_image
    open_ai_service = OpenAiService.new
    @response_text = open_ai_service.chat_with_image("What’s in this image?", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg")
    
    # Use @response_text in your view or return it as JSON
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-8">
    <div class="h1-like">Bienvenue dans le monde des plantes</div>
  </div>

  
  <%= form_with(url: rechercher_path, method: "get", local: true) do |form| %>
    <div class="flex justify-between items-center mb-8">
      <div class="h2-like"><%= form.label :query, "Rechercher une plante:" %></div>
      <%= form.text_field :query %>
      <%= form.submit "Voir", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
    </div>
  <% end %>
  

  <br>
  <div class="flex justify-between items-center mb-8">
    <div class="h2-like">Types de plantes</div>
    <%= link_to "Voir", types_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>

  <div class="flex justify-between items-center mb-8">
    <div class="h2-like">Familles de plantes</div>
    <%= link_to "Voir", familles_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>

  <div class="flex justify-between items-center mb-8">
    <div class="h2-like">Plantes</div>
    <%= link_to "Voir", plantes_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>